hm,
chrisjulia@tes15:~/julia-experiments/chris-oo$ julia foo.jl
110
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{Foo}, ::Int64, ::Int64)
This may have arisen from a call to the constructor Foo(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
 in call at ./essentials.jl:57
while loading /home/chrisjulia/julia-experiments/chris-oo/foo.jl, in expression starting on line 18